---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/todos":
    post:
      summary: Create a todo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "est"
                created_by:
                  type: string
                  example: "1"
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: "iure"
                      done:
                        type: boolean
                        example: false
      responses:
        '201':
          description: Todo created
        '422':
          description: Invalid request
  "/todos/{id}":
    get:
      summary: Retrieves a todo
      tags:
      - Todos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: todo found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  created_by:
                    type: integer
                required:
                - id
                - title
                - created_by
        '404':
          description: todo not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
