// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "jquery"
import "jquery_ujs"
import "bootstrap"
import "posts/style"
import "posts/modal"
import "posts/infinite_scroll"
import "channels/private/conversation_channel"
import "./conversations/conversation.js"
import "./messages/position_and_visibility"
import "./messages/toggle_window"
import "./messages/messages_infinite_scroll.js"
//= require jquery
//= require bootstrap-sprocketsimport "channels"
